spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 10
      maxActive: 30
      minIdle: 5
      maxWait: 2000
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 3
        max-wait: 3000
  mail:
    host: smtp.qq.com
    username: 1107064862@qq.com  #邮箱名,一定要用你自己的
    password: bhwrekutqflsiibj # 邮箱授权码,一定要用你自己的
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual

  elasticsearch:
    rest:
      uris: http://localhost:9200

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.czy.qiantai.vo
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto


